/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

import ConexionBD.ConexionBD;
import Controlador.MedicoDAO;
import Modelo.Medico;
import Modelo.ResultSetTableModel;
import com.sun.source.tree.CatchTree;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author erick
 */
public class Dg_MedicosBajas extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dg_MedicosBajas.class.getName());

    /**
     * Creates new form Dg_MedicosBajas
     */
    
    private javax.swing.JTable tablaRegMedicos;
    
    MedicoDAO medicoDAO = MedicoDAO.getInstancia();
    ConexionBD conexionBD = ConexionBD.getInstancia();
    
    public Dg_MedicosBajas(java.awt.Frame parent, boolean modal, javax.swing.JTable tablaRegMedicos) {
        super(parent, modal);
        this.tablaRegMedicos = tablaRegMedicos;
        initComponents();
        setTitle("Eliminar Médico");  
        setSize(380, 450);           
        setLocationRelativeTo(null);  
        setResizable(false); 
        
        
        cajaNombreBajas.setEnabled(false);
        cajaPaternoBajas.setEnabled(false);
        cajaMaternoBajas.setEnabled(false);
        cbEspecialidadBajas.setEnabled(false);
        cajaExperienciaBajas.setEnabled(false);
        btnEliminarMedBajas.setEnabled(false);
        btnRestablecerMedBajas.setEnabled(false);
    }
    
    
    public void limpiarCampos(){
        cajaSSNBajas.setText("");
        cajaNombreBajas.setText("");
        cajaPaternoBajas.setText("");
        cajaMaternoBajas.setText("");
        cbEspecialidadBajas.setSelectedIndex(0);
        cajaExperienciaBajas.setText("");
        btnEliminarMedBajas.setEnabled(false);
        btnRestablecerMedBajas.setEnabled(false);
    }
    
    /*
    public void obtenerDatosMedico(){
        
        medicoDAO.actualizarTabla(tablaRegMedicos);
        String sql = "SELECT * FROM Medicos WHERE SSN = ?";

        ResultSet rs = conexionBD.ejecutarConsultaSQL(sql, cajaSSNBajas.getText());
        
        try {
            if (rs != null && rs.next()) {

                cajaNombreBajas.setText(rs.getString("Nombre"));
                cajaPaternoBajas.setText(rs.getString("Ape_Paterno"));
                cajaMaternoBajas.setText(rs.getString("Ape_Materno"));
                cbEspecialidadBajas.setSelectedItem(rs.getString("Especialidad"));
                cajaExperienciaBajas.setText(rs.getString("Años_Experiencia"));

        }   else {
                JOptionPane.showMessageDialog(null, "No se encontró un medico con ese SSN.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al obtener los datos del Medico.");
        }
        
        
    }
    */
    
    public void obtenerDatosMedico() {

    String sql = "SELECT * FROM Medicos WHERE SSN LIKE ?";
    String texto = cajaSSNBajas.getText().trim() + "%";

    ResultSet rs = conexionBD.ejecutarConsultaSQL(sql, texto);

    // Actualizar tabla según coincidencias
    medicoDAO.actualizarTablaFiltrada(cajaSSNBajas.getText(), texto);

    try {
        if (rs != null && rs.next()) {
            // Mostrar datos del primero, si coincide
            cajaNombreBajas.setText(rs.getString("Nombre"));
            cajaPaternoBajas.setText(rs.getString("Ape_Paterno"));
            cajaMaternoBajas.setText(rs.getString("Ape_Materno"));
            cbEspecialidadBajas.setSelectedItem(rs.getString("Especialidad"));
            cajaExperienciaBajas.setText(rs.getString("Años_Experiencia"));
        } else {
            // Limpiar campos si no hay coincidencias exactas
            cajaNombreBajas.setText("");
            cajaPaternoBajas.setText("");
            cajaMaternoBajas.setText("");
            cbEspecialidadBajas.setSelectedItem(null);
            cajaExperienciaBajas.setText("");
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al obtener los datos del Médico.");
    }
}

    
        
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cajaSSNBajas = new javax.swing.JTextField();
        cajaNombreBajas = new javax.swing.JTextField();
        cajaPaternoBajas = new javax.swing.JTextField();
        btnBuscarBajas = new javax.swing.JButton();
        cajaMaternoBajas = new javax.swing.JTextField();
        cajaExperienciaBajas = new javax.swing.JTextField();
        btnRestablecerMedBajas = new javax.swing.JButton();
        btnEliminarMedBajas = new javax.swing.JButton();
        cbEspecialidadBajas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("SSN");

        jLabel2.setText("Nombres(s)");

        jLabel3.setText("Apellido Paterno");

        jLabel4.setText("Apellido Materno");

        jLabel5.setText("Especialidad");

        jLabel6.setText("Años Experiencia");

        cajaSSNBajas.setBackground(new java.awt.Color(51, 153, 255));
        cajaSSNBajas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaSSNBajasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaSSNBajasKeyTyped(evt);
            }
        });

        btnBuscarBajas.setText("Buscar");
        btnBuscarBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarBajasActionPerformed(evt);
            }
        });

        btnRestablecerMedBajas.setBackground(new java.awt.Color(0, 153, 255));
        btnRestablecerMedBajas.setForeground(new java.awt.Color(0, 0, 0));
        btnRestablecerMedBajas.setText("Restablecer");
        btnRestablecerMedBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerMedBajasActionPerformed(evt);
            }
        });

        btnEliminarMedBajas.setBackground(new java.awt.Color(0, 153, 255));
        btnEliminarMedBajas.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarMedBajas.setText("Eliminar");
        btnEliminarMedBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMedBajasActionPerformed(evt);
            }
        });

        cbEspecialidadBajas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige Especialidad...", "Cardiología", "Pediatría", "Ginecología", "Medicina General", "Dermatología", "Neurología", "Oncología", "Oftalmología" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cajaPaternoBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaNombreBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbEspecialidadBajas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cajaMaternoBajas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cajaSSNBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnEliminarMedBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cajaExperienciaBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnRestablecerMedBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(cajaSSNBajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaNombreBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaPaternoBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaMaternoBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(cbEspecialidadBajas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaExperienciaBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRestablecerMedBajas, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnEliminarMedBajas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestablecerMedBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerMedBajasActionPerformed
        limpiarCampos();
        ResultSetTableModel modelo = medicoDAO.actualizarTablaFiltrada("SSN", cajaSSNBajas.getText());
        tablaRegMedicos.setModel(modelo);
    }//GEN-LAST:event_btnRestablecerMedBajasActionPerformed

    private void btnBuscarBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarBajasActionPerformed
        
        if (cajaSSNBajas.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Campo vacio, verifica el campo 'SSN'");
            }
         
        
        if (cajaSSNBajas.getText().length() != 11) {
            JOptionPane.showMessageDialog(this, "Debes ingresar exactamente 11 caracteres",
            "SSN inválido", JOptionPane.ERROR_MESSAGE);
            return;
            }
         
         
        Medico medico = MedicoDAO.getInstancia().buscarMedicoPorSSN(cajaSSNBajas.getText());

        if (medico == null) {
            JOptionPane.showMessageDialog(this,
                "No existe un médico con ese SSN.",
                "Sin resultados",
                JOptionPane.INFORMATION_MESSAGE);
            cajaSSNBajas.setText("");
            medicoDAO.actualizarTabla(tablaRegMedicos);
            return;
        }
            
        try {   
            obtenerDatosMedico();
            btnEliminarMedBajas.setEnabled(true);
            btnRestablecerMedBajas.setEnabled(true);
        } catch (RuntimeException ex) {
                JOptionPane.showMessageDialog(this,"Error al obtener los datos del médico");
        }
    }//GEN-LAST:event_btnBuscarBajasActionPerformed

    private void btnEliminarMedBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMedBajasActionPerformed
        
        String ssn = cajaSSNBajas.getText().trim();

        if (ssn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero ingrese un SSN valido",
            "Dato invalido", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        

        // 1. Verificar si tiene pacientes
        int pacientes = medicoDAO.contarPacientesDeMedico(ssn);

        if (pacientes > 0) {
            // 2. Mostrar advertencia
            int opcion = JOptionPane.showConfirmDialog(
                this,
                "Este médico tiene " + pacientes + " pacientes asignados.\n" +
                "¿Seguro que desea eliminarlo?\n\n" +
                "(Esto también eliminará a los pacientes que dependan de él.)",
                "Advertencia",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return; 
        }
        
    }
        
         if (medicoDAO.eliminarMedico(cajaSSNBajas.getText())){

                medicoDAO.actualizarTabla(tablaRegMedicos);
                JOptionPane.showMessageDialog(this, "Registro eliminado correctamente");
            }else {
                JOptionPane.showMessageDialog(this, "ERROR al eliminar el registro",
                "No existe ese SSN", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnEliminarMedBajasActionPerformed

    private void cajaSSNBajasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaSSNBajasKeyReleased
        ResultSetTableModel modelo = medicoDAO.actualizarTablaFiltrada("SSN", cajaSSNBajas.getText());
        tablaRegMedicos.setModel(modelo);
    }//GEN-LAST:event_cajaSSNBajasKeyReleased

    private void cajaSSNBajasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaSSNBajasKeyTyped
        
        char c = evt.getKeyChar();

        
        if (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            return;
        }
        
        if (cajaSSNBajas.getText().length() >= 11) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar 11 caracteres");
            return;
        }

        if (!Character.isDigit(c)) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar números");
        }
    }//GEN-LAST:event_cajaSSNBajasKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
   

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            JTable tablaDummy = new JTable();
            @Override
            public void run() {
                Dg_MedicosBajas dialog = new Dg_MedicosBajas(new javax.swing.JFrame(), true, tablaDummy);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarBajas;
    private javax.swing.JButton btnEliminarMedBajas;
    private javax.swing.JButton btnRestablecerMedBajas;
    private javax.swing.JTextField cajaExperienciaBajas;
    private javax.swing.JTextField cajaMaternoBajas;
    private javax.swing.JTextField cajaNombreBajas;
    private javax.swing.JTextField cajaPaternoBajas;
    private javax.swing.JTextField cajaSSNBajas;
    private javax.swing.JComboBox<String> cbEspecialidadBajas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
