/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

import Controlador.MedicoDAO;
import Modelo.Medico;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author erick
 */
public class Dg_MedicosAltas extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dg_MedicosAltas.class.getName());

    /**
     * Creates new form Dg_Medicos
     */
    
    MedicoDAO medicoDAO = MedicoDAO.getInstancia();
    
    private javax.swing.JTable tablaRegMedicos;
    
    public Dg_MedicosAltas(java.awt.Frame parent, boolean modal, javax.swing.JTable tablaRegMedicos) {
        super(parent, modal);
        this.tablaRegMedicos = tablaRegMedicos;
        initComponents();
        setTitle("Agregar Médico");  
        setSize(380, 450);           
        setLocationRelativeTo(null);  
        setResizable(false); 

    }
    
    
    public void limpiarCampos(){
        cajaSSNAltas.setText("");
        cajaNombreAltas.setText("");
        cajaPaternoAltas.setText("");
        cajaMaternoAltas.setText("");
        cbEspecialidadAltas.setSelectedIndex(0);
        cajaExperienciaAltas.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cajaSSNAltas = new javax.swing.JTextField();
        cajaNombreAltas = new javax.swing.JTextField();
        cajaPaternoAltas = new javax.swing.JTextField();
        cajaMaternoAltas = new javax.swing.JTextField();
        cbEspecialidadAltas = new javax.swing.JComboBox<>();
        cajaExperienciaAltas = new javax.swing.JTextField();
        btnAgregarMedAltas = new javax.swing.JButton();
        btnRestablecerMedAltas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setText("SSN");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido Paterno");

        jLabel4.setText("Apellido Materno");

        jLabel5.setText("Especialidad");

        jLabel6.setText("Años Experiencia");

        cajaSSNAltas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaSSNAltasKeyTyped(evt);
            }
        });

        cajaNombreAltas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaNombreAltasKeyTyped(evt);
            }
        });

        cajaPaternoAltas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaPaternoAltasKeyTyped(evt);
            }
        });

        cajaMaternoAltas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaMaternoAltasKeyTyped(evt);
            }
        });

        cbEspecialidadAltas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige Especialidad...", "Cardiología", "Pediatría", "Ginecología", "Medicina General", "Dermatología", "Neurología", "Oncología", "Oftalmología" }));

        cajaExperienciaAltas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaExperienciaAltasKeyTyped(evt);
            }
        });

        btnAgregarMedAltas.setBackground(new java.awt.Color(0, 153, 255));
        btnAgregarMedAltas.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnAgregarMedAltas.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarMedAltas.setText("Agregar");
        btnAgregarMedAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMedAltasActionPerformed(evt);
            }
        });

        btnRestablecerMedAltas.setBackground(new java.awt.Color(0, 153, 255));
        btnRestablecerMedAltas.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnRestablecerMedAltas.setForeground(new java.awt.Color(0, 0, 0));
        btnRestablecerMedAltas.setText("Restablecer");
        btnRestablecerMedAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerMedAltasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cajaSSNAltas)
                    .addComponent(cajaNombreAltas)
                    .addComponent(cajaPaternoAltas)
                    .addComponent(cajaMaternoAltas)
                    .addComponent(cbEspecialidadAltas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cajaExperienciaAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnRestablecerMedAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarMedAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaSSNAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cajaNombreAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaPaternoAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaMaternoAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEspecialidadAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaExperienciaAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarMedAltas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRestablecerMedAltas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMedAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMedAltasActionPerformed
        
        if (cajaSSNAltas.getText().isEmpty() || cajaNombreAltas.getText().isEmpty() 
            || cajaPaternoAltas.getText().isEmpty() 
            || cajaMaternoAltas.getText().isEmpty() 
            || cajaExperienciaAltas.getText().isEmpty()){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this,"Asegurate de llenar TODOS los campos correctamente!",
                    "Campo inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (cajaSSNAltas.getText().length() != 11) {
            JOptionPane.showMessageDialog(this, "El SSN debe contener exactamente 11 caracteres",
            "SSN inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (cbEspecialidadAltas.getSelectedItem().toString().equals("Elige Especialidad...")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this,"Selecciona una especialidad valida",
                    "Campo inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String exp = cajaExperienciaAltas.getText().trim();
        
        try {
            byte experiencia = Byte.parseByte(exp);

            if (experiencia < 1 || experiencia > 60) {
                JOptionPane.showMessageDialog(this,
                    "Los años de experiencia deben estar entre 1 y 60.",
                    "Dato inválido", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Introduce un número válido para los años de experiencia.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Medico m = new Medico(cajaSSNAltas.getText().trim(),
                cajaNombreAltas.getText(),
                cajaPaternoAltas.getText(),
                cajaMaternoAltas.getText(),
                cbEspecialidadAltas.getSelectedItem().toString(),
                Byte.parseByte(cajaExperienciaAltas.getText()));
        
        
        if (medicoDAO.agregarMedico(m)) {
                JOptionPane.showMessageDialog(this,"Registro Agregado CORRECTAMENTE");
                System.out.println("Registro Agregado CORRECTAMENTE");
                System.out.println("ejecutando");
                
                medicoDAO.actualizarTabla(tablaRegMedicos);
        }else{
                    JOptionPane.showMessageDialog(this,"Error en la insercion");
                    System.out.println("ERROR en la insercion");
             }
    }//GEN-LAST:event_btnAgregarMedAltasActionPerformed

    private void btnRestablecerMedAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerMedAltasActionPerformed
        
        
        if (cajaNombreAltas.getText().isEmpty() && cajaPaternoAltas.getText().isEmpty() 
                && cajaMaternoAltas.getText().isEmpty() && cbEspecialidadAltas.getSelectedItem().toString().equals("Elige Especialidad...")
                && cajaExperienciaAltas.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(this, "No hay datos para eliminar");
            
        }
        limpiarCampos();
    }//GEN-LAST:event_btnRestablecerMedAltasActionPerformed

    private void cajaSSNAltasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaSSNAltasKeyTyped
        
        char c = evt.getKeyChar();

        
        if (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            return;
        }

        
        if (cajaSSNAltas.getText().length() >= 11) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar 11 caracteres");
            return;
        }
        

        
        if (!Character.isDigit(c)) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar números");
        }
        
     
    }//GEN-LAST:event_cajaSSNAltasKeyTyped

    private void cajaNombreAltasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaNombreAltasKeyTyped
        
        char c = evt.getKeyChar();

        
        if (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            return;
        }

        
        if (c == ' ') {
            return;
        }
        
        if (cajaNombreAltas.getText().length() >= 50) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar 50 caracteres");
            return;
        }

        if (!Character.isLetter(c)) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar letras");
        }
    }//GEN-LAST:event_cajaNombreAltasKeyTyped

    private void cajaPaternoAltasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaPaternoAltasKeyTyped
        
        char c = evt.getKeyChar();

        
        if (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            return;
        }

        
        if (c == ' ') {
            return;
        }

        if (cajaPaternoAltas.getText().length() >= 50) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar 50 caracteres");
            return;
        }
        
        if (!Character.isLetter(c)) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar letras");
        }
    }//GEN-LAST:event_cajaPaternoAltasKeyTyped

    private void cajaMaternoAltasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaMaternoAltasKeyTyped
        
        char c = evt.getKeyChar();

        
        if (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            return;
        }

        
        if (c == ' ') {
            return;
        }

        if (cajaMaternoAltas.getText().length() >= 50) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar 50 caracteres");
            return;
        }
        
        if (!Character.isLetter(c)) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar letras");
        }
    }//GEN-LAST:event_cajaMaternoAltasKeyTyped

    private void cajaExperienciaAltasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaExperienciaAltasKeyTyped
        
        char c = evt.getKeyChar();

        
        if (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            return;
        }

        
        if (cajaExperienciaAltas.getText().length() >= 2) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar 2 caracteres");
            return;
        }

        
        if (!Character.isDigit(c)) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar números");
        }
    }//GEN-LAST:event_cajaExperienciaAltasKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            JTable tablaDummy = new JTable();
            @Override
            public void run() {
                Dg_MedicosAltas dialog = new Dg_MedicosAltas(new javax.swing.JFrame(), true, tablaDummy);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMedAltas;
    private javax.swing.JButton btnRestablecerMedAltas;
    private javax.swing.JTextField cajaExperienciaAltas;
    private javax.swing.JTextField cajaMaternoAltas;
    private javax.swing.JTextField cajaNombreAltas;
    private javax.swing.JTextField cajaPaternoAltas;
    private javax.swing.JTextField cajaSSNAltas;
    private javax.swing.JComboBox<String> cbEspecialidadAltas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
