/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

import ConexionBD.ConexionBD;
import Controlador.MedicoDAO;
import Modelo.Medico;
import Modelo.ResultSetTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author erick
 */
public class Dg_MedicosCambios extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dg_MedicosCambios.class.getName());

    /**
     * Creates new form Dg_MedicosCambios
     */
    ConexionBD conexionBD = ConexionBD.getInstancia();
    MedicoDAO medicoDAO = MedicoDAO.getInstancia();
    private javax.swing.JTable tablaRegMedicos;
    
    
    public Dg_MedicosCambios(java.awt.Frame parent, boolean modal, javax.swing.JTable tablaRegMedicos) {
        super(parent, modal);
        this.tablaRegMedicos = tablaRegMedicos;
        initComponents();
        setTitle("Modificar Médico");  
        setSize(380, 450);           
        setLocationRelativeTo(null);  
        setResizable(false); 
        
        
        cajaNombreCambios.setEnabled(false);
        cajaPaternoCambios.setEnabled(false);
        cajaMaternoCambios.setEnabled(false);
        cbEspecialidadCambios.setEnabled(false);
        cajaExperienciaCambios.setEnabled(false);
    }
    
    /*
    public void obtenerDatosMedico(){
        
        String sql = "SELECT * FROM Medicos WHERE SSN = ?";
        
        ResultSet rs = conexionBD.ejecutarConsultaSQL(sql, cajaSSNCambios.getText());
        
        try {
            if (rs != null && rs.next()) {

                cajaNombreCambios.setText(rs.getString("Nombre"));
                cajaPaternoCambios.setText(rs.getString("Ape_Paterno"));
                cajaMaternoCambios.setText(rs.getString("Ape_Materno"));
                cbEspecialidadCambios.setSelectedItem(rs.getString("Especialidad"));
                cajaExperienciaCambios.setText(rs.getString("Años_Experiencia"));
                
                habilitarCamposEdicion(true);

        }   else {
                JOptionPane.showMessageDialog(null, "No se encontró un medico con ese SSN.");
                habilitarCamposEdicion(false);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al obtener los datos del Medico.");
        }
    }
    */
    
    
    public void obtenerDatosMedico() {

    String sql = "SELECT * FROM Medicos WHERE SSN LIKE ?";
    String texto = cajaSSNCambios.getText().trim() + "%";

    ResultSet rs = conexionBD.ejecutarConsultaSQL(sql, texto);

    // Actualizar tabla según coincidencias
    medicoDAO.actualizarTablaFiltrada(cajaSSNCambios.getText(), texto);

    try {
        if (rs != null && rs.next()) {
            // Mostrar datos del primero, si coincide
            cajaNombreCambios.setText(rs.getString("Nombre"));
            cajaPaternoCambios.setText(rs.getString("Ape_Paterno"));
            cajaMaternoCambios.setText(rs.getString("Ape_Materno"));
            cbEspecialidadCambios.setSelectedItem(rs.getString("Especialidad"));
            cajaExperienciaCambios.setText(rs.getString("Años_Experiencia"));
            
            habilitarCamposEdicion(true);
            
        } else {
            // Limpiar campos si no hay coincidencias exactas
            cajaNombreCambios.setText("");
            cajaPaternoCambios.setText("");
            cajaMaternoCambios.setText("");
            cbEspecialidadCambios.setSelectedItem(null);
            cajaExperienciaCambios.setText("");
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al obtener los datos del Médico.");
    }
}
    
    
    
    public void habilitarCamposEdicion(boolean habilitar){
        cajaNombreCambios.setEnabled(habilitar);
        cajaPaternoCambios.setEnabled(habilitar);
        cajaMaternoCambios.setEnabled(habilitar);
        cbEspecialidadCambios.setEnabled(habilitar);
        cajaExperienciaCambios.setEnabled(habilitar);
    }
    
    
    public void limpiarCampos(){
        cajaSSNCambios.setText("");
        cajaNombreCambios.setText("");
        cajaPaternoCambios.setText("");
        cajaMaternoCambios.setText("");
        cbEspecialidadCambios.setSelectedIndex(0);
        cajaExperienciaCambios.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cajaSSNCambios = new javax.swing.JTextField();
        cajaNombreCambios = new javax.swing.JTextField();
        cajaPaternoCambios = new javax.swing.JTextField();
        cajaMaternoCambios = new javax.swing.JTextField();
        cajaExperienciaCambios = new javax.swing.JTextField();
        cbEspecialidadCambios = new javax.swing.JComboBox<>();
        btnBuscarCambios = new javax.swing.JButton();
        btnRestablecerMedCambios = new javax.swing.JButton();
        btnEditarMedCambios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("SSN");

        jLabel2.setText("Nombre(s)");

        jLabel3.setText("Apellido Paterno");

        jLabel4.setText("Apellido Materno");

        jLabel5.setText("Especialidad");

        jLabel6.setText("Años Experiencia");

        cajaSSNCambios.setBackground(new java.awt.Color(51, 153, 255));
        cajaSSNCambios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaSSNCambiosKeyReleased(evt);
            }
        });

        cbEspecialidadCambios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige Especialidad...", "Cardiología", "Pediatría", "Ginecología", "Medicina General", "Dermatología", "Neurología", "Oncología", "Oftalmología" }));

        btnBuscarCambios.setText("Buscar");
        btnBuscarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCambiosActionPerformed(evt);
            }
        });

        btnRestablecerMedCambios.setBackground(new java.awt.Color(255, 153, 0));
        btnRestablecerMedCambios.setForeground(new java.awt.Color(0, 0, 0));
        btnRestablecerMedCambios.setText("Restablecer");
        btnRestablecerMedCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerMedCambiosActionPerformed(evt);
            }
        });

        btnEditarMedCambios.setBackground(new java.awt.Color(255, 153, 0));
        btnEditarMedCambios.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarMedCambios.setText("Editar");
        btnEditarMedCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMedCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cajaSSNCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnRestablecerMedCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditarMedCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cajaNombreCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cajaPaternoCambios))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cajaMaternoCambios))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cbEspecialidadCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cajaExperienciaCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cajaSSNCambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaNombreCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaPaternoCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaMaternoCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEspecialidadCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaExperienciaCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestablecerMedCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarMedCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestablecerMedCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerMedCambiosActionPerformed
        
        habilitarCamposEdicion(false);
            if (cajaSSNCambios.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"No hay datos para borrar");
            }
            limpiarCampos();
             ResultSetTableModel modelo = medicoDAO.actualizarTablaFiltrada("SSN", cajaSSNCambios.getText());
        tablaRegMedicos.setModel(modelo);
    }//GEN-LAST:event_btnRestablecerMedCambiosActionPerformed

    private void btnBuscarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCambiosActionPerformed
        
        if (cajaSSNCambios.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Campo vacio, verifica campo 'SSN'");
            } else {

                obtenerDatosMedico();
            }
    }//GEN-LAST:event_btnBuscarCambiosActionPerformed

    private void btnEditarMedCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMedCambiosActionPerformed
        
        
        Medico m = new Medico(cajaSSNCambios.getText().trim(),
                cajaNombreCambios.getText(),
                cajaPaternoCambios.getText(),
                cajaMaternoCambios.getText(),
                cbEspecialidadCambios.getSelectedItem().toString(),
                Byte.parseByte(cajaExperienciaCambios.getText()));
        
        
        if (medicoDAO.editarMedico(m)) {
                JOptionPane.showMessageDialog(this,"Registro Editado CORRECTAMENTE");
                medicoDAO.actualizarTabla(tablaRegMedicos);
                
        }else{
                    JOptionPane.showMessageDialog(this,"ERROR, al editar registro");
                  
             }
    }//GEN-LAST:event_btnEditarMedCambiosActionPerformed

    private void cajaSSNCambiosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaSSNCambiosKeyReleased
        
        ResultSetTableModel modelo = medicoDAO.actualizarTablaFiltrada("SSN", cajaSSNCambios.getText());
        tablaRegMedicos.setModel(modelo);
    }//GEN-LAST:event_cajaSSNCambiosKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
             JTable tablaDummy = new JTable();
            @Override
            public void run() {
                Dg_MedicosCambios dialog = new Dg_MedicosCambios(new javax.swing.JFrame(), true, tablaDummy);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCambios;
    private javax.swing.JButton btnEditarMedCambios;
    private javax.swing.JButton btnRestablecerMedCambios;
    private javax.swing.JTextField cajaExperienciaCambios;
    private javax.swing.JTextField cajaMaternoCambios;
    private javax.swing.JTextField cajaNombreCambios;
    private javax.swing.JTextField cajaPaternoCambios;
    private javax.swing.JTextField cajaSSNCambios;
    private javax.swing.JComboBox<String> cbEspecialidadCambios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
