/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

import Controlador.MedicoDAO;
import Controlador.PacienteDAO;
import Modelo.Paciente;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;

/**
 *
 * @author erick
 */
public class Dg_PacientesAltas extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dg_PacientesAltas.class.getName());

    /**
     * Creates new form Dg_PacientesAltas
     */
    
    PacienteDAO pacienteDAO = PacienteDAO.getInstancia();
    
    private javax.swing.JTable tablaRegPacientes;
    
    public Dg_PacientesAltas(java.awt.Frame parent, boolean modal, javax.swing.JTable tablaRegPacientes) {
        super(parent, modal);
        this.tablaRegPacientes = tablaRegPacientes;
        initComponents();
        setTitle("Agregar Paciente");  
        setSize(380, 640);           
        setLocationRelativeTo(null);  
        setResizable(false); 
        ((JSpinner.DefaultEditor) spEdadAltas.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor) spEdadAltas.getEditor()).getTextField().setFocusable(false);

        cargarMedicosEnCombo(); 
    }
    
    
    public void cargarMedicosEnCombo() {
    cbSSNMedicoAltas.removeAllItems();  // Limpia combo antes de recargar

    ResultSet rs = pacienteDAO.obtenerTodosLosMedicos();

    try {
        while (rs.next()) {
            String ssn = rs.getString("SSN");
            
            cbSSNMedicoAltas.addItem(ssn);
            
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al cargar médicos");
    }
}
    
    private void actualizarLabelMedico() {
    if (cbSSNMedicoAltas.getSelectedItem() == null) return;

    String ssn = cbSSNMedicoAltas.getSelectedItem().toString();

    String nombre = MedicoDAO.getInstancia().obtenerNombreCompleto(ssn);

    lblNombreMedAltas.setText("Médico asignado: " + nombre);
}
    
    public void limpiarCampos(){
        cajaSSNAltas.setText("");
        cajaNombreAltas.setText("");
        cajaPaternoAltas.setText("");
        cajaMaternoAltas.setText("");
        spEdadAltas.setValue(0);
        cbSSNMedicoAltas.setSelectedIndex(0);
        cajaCalleAltas.setText("");
        cajaNumAltas.setText("");
        cajaColoniaAltas.setText("");
        cajaCodPostalAltas.setText("");
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnRestablecerPacAltas = new javax.swing.JButton();
        cajaSSNAltas = new javax.swing.JTextField();
        cajaNombreAltas = new javax.swing.JTextField();
        cajaPaternoAltas = new javax.swing.JTextField();
        cajaMaternoAltas = new javax.swing.JTextField();
        spEdadAltas = new javax.swing.JSpinner();
        cbSSNMedicoAltas = new javax.swing.JComboBox<>();
        cajaCalleAltas = new javax.swing.JTextField();
        cajaNumAltas = new javax.swing.JTextField();
        cajaColoniaAltas = new javax.swing.JTextField();
        cajaCodPostalAltas = new javax.swing.JTextField();
        btnAgregarPacAltas = new javax.swing.JButton();
        lblNombreMedAltas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("SSN");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido Paterno");

        jLabel4.setText("Apellido Materno");

        jLabel5.setText("Edad");

        jLabel6.setText("SSN Medico");

        jLabel7.setText("Calle");

        jLabel8.setText("Numero");

        jLabel9.setText("Colonia");

        jLabel10.setText("Codigo Postal");

        btnRestablecerPacAltas.setBackground(new java.awt.Color(0, 153, 255));
        btnRestablecerPacAltas.setForeground(new java.awt.Color(0, 0, 0));
        btnRestablecerPacAltas.setText("Restablecer");
        btnRestablecerPacAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerPacAltasActionPerformed(evt);
            }
        });

        cajaSSNAltas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaSSNAltasKeyTyped(evt);
            }
        });

        cajaNombreAltas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaNombreAltasKeyTyped(evt);
            }
        });

        cajaPaternoAltas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaPaternoAltasKeyTyped(evt);
            }
        });

        cajaMaternoAltas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaMaternoAltasKeyTyped(evt);
            }
        });

        spEdadAltas.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        cbSSNMedicoAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSSNMedicoAltasActionPerformed(evt);
            }
        });

        cajaCalleAltas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaCalleAltasKeyTyped(evt);
            }
        });

        cajaNumAltas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaNumAltasKeyTyped(evt);
            }
        });

        cajaColoniaAltas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaColoniaAltasKeyTyped(evt);
            }
        });

        cajaCodPostalAltas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaCodPostalAltasKeyTyped(evt);
            }
        });

        btnAgregarPacAltas.setBackground(new java.awt.Color(0, 153, 255));
        btnAgregarPacAltas.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarPacAltas.setText("Agregar");
        btnAgregarPacAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPacAltasActionPerformed(evt);
            }
        });

        lblNombreMedAltas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRestablecerPacAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(btnAgregarPacAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblNombreMedAltas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cajaSSNAltas)
                                .addComponent(cajaNombreAltas)
                                .addComponent(cajaPaternoAltas)
                                .addComponent(cajaMaternoAltas)
                                .addComponent(cbSSNMedicoAltas, 0, 200, Short.MAX_VALUE)
                                .addComponent(cajaCalleAltas)
                                .addComponent(cajaNumAltas)
                                .addComponent(cajaColoniaAltas)
                                .addComponent(cajaCodPostalAltas)
                                .addComponent(spEdadAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cajaSSNAltas, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaNombreAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaPaternoAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaMaternoAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spEdadAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreMedAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSSNMedicoAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaCalleAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaNumAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaColoniaAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaCodPostalAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestablecerPacAltas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarPacAltas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPacAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPacAltasActionPerformed
        
        int edad = (int) spEdadAltas.getValue();
        if (cajaSSNAltas.getText().isEmpty() || cajaNombreAltas.getText().isEmpty() 
                || cajaPaternoAltas.getText().isEmpty() || cajaMaternoAltas.getText().isEmpty()
                || edad == 0 || cbSSNMedicoAltas.getSelectedItem().toString().isEmpty()
                || cajaCalleAltas.getText().isEmpty() || cajaNumAltas.getText().isEmpty()
                || cajaColoniaAltas.getText().isEmpty() || cajaCodPostalAltas.getText().isEmpty()){
            
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this,"Asegurate de llenar TODOS los campos correctamente!",
                    "Campo inválido", JOptionPane.ERROR_MESSAGE);
            return;
            
        }
        
        if (cajaSSNAltas.getText().length() != 11) {
            JOptionPane.showMessageDialog(this, "Debes ingresar exactamente 11 caracteres",
            "SSN Invalido", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (cajaCodPostalAltas.getText().length() != 5){
            JOptionPane.showMessageDialog(this, "Debes ingresar exactamente 5 numeros",
                    "Cod_Postal invalido", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (edad < 1 || edad > 100) {
            JOptionPane.showMessageDialog(this,
                "La edad debe estar entre 1 y 100 años.",
                "Edad inválida",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        
        
        Paciente p = new Paciente(cajaSSNAltas.getText(),
                cajaNombreAltas.getText(),
                cajaPaternoAltas.getText(),
                cajaMaternoAltas.getText(),
                Byte.parseByte(spEdadAltas.getValue().toString()),
                cbSSNMedicoAltas.getSelectedItem().toString(),
                cajaCalleAltas.getText(),
                Integer.parseInt(cajaNumAltas.getText()),
                cajaColoniaAltas.getText(),
                Integer.parseInt(cajaCodPostalAltas.getText()));
        
        if (pacienteDAO.agregarPaciente(p)) {
                JOptionPane.showMessageDialog(this,"Registro Agregado CORRECTAMENTE");
                System.out.println("Registro Agregado CORRECTAMENTE");
                
                pacienteDAO.actualizarTabla(tablaRegPacientes);
        }else{
                    JOptionPane.showMessageDialog(this,"Error en la insercion");
                    System.out.println("ERROR en la insercion");
             }
        
    }//GEN-LAST:event_btnAgregarPacAltasActionPerformed

    private void cbSSNMedicoAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSSNMedicoAltasActionPerformed
       
        actualizarLabelMedico();
    }//GEN-LAST:event_cbSSNMedicoAltasActionPerformed

    private void btnRestablecerPacAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerPacAltasActionPerformed
       int edad = (int) spEdadAltas.getValue();
        if (cajaSSNAltas.getText().isEmpty() &&  cajaNombreAltas.getText().isEmpty() && cajaPaternoAltas.getText().isEmpty() && cajaMaternoAltas.getText().isEmpty()
                && edad == 0 && cbSSNMedicoAltas.getSelectedIndex() == 0
                && cajaCalleAltas.getText().isEmpty() && cajaNumAltas.getText().isEmpty()
                && cajaColoniaAltas.getText().isEmpty() && cajaCodPostalAltas.getText().isEmpty()){
            
           
        JOptionPane.showMessageDialog(this,"No hay elementos que eliminar");
        return;
            
        }
       limpiarCampos();
    }//GEN-LAST:event_btnRestablecerPacAltasActionPerformed

    private void cajaSSNAltasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaSSNAltasKeyTyped
        
        char c = evt.getKeyChar();

        
        if (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            return;
        }

        
        if (cajaSSNAltas.getText().length() >= 11) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar 11 caracteres");
            return;
        }

        
        if (!Character.isDigit(c)) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar números");
        }
    }//GEN-LAST:event_cajaSSNAltasKeyTyped

    private void cajaNombreAltasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaNombreAltasKeyTyped
        
        char c = evt.getKeyChar();

        
        if (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            return;
        }

        
        if (c == ' ') {
            return;
        }
        
        if (cajaNombreAltas.getText().length() >= 50) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar 50 caracteres");
            return;
        }

        
        if (!Character.isLetter(c)) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar letras");
        }
    }//GEN-LAST:event_cajaNombreAltasKeyTyped

    private void cajaPaternoAltasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaPaternoAltasKeyTyped
        
        char c = evt.getKeyChar();

        
        if (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            return;
        }

        
        if (c == ' ') {
            return;
        }
        
        if (cajaPaternoAltas.getText().length() >= 50) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar 50 caracteres");
            return;
        }

        
        if (!Character.isLetter(c)) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar letras");
        }
    }//GEN-LAST:event_cajaPaternoAltasKeyTyped

    private void cajaMaternoAltasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaMaternoAltasKeyTyped
        
        char c = evt.getKeyChar();

        
        if (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            return;
        }

        
        if (c == ' ') {
            return;
        }
        
        if (cajaMaternoAltas.getText().length() >= 50) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar 50 caracteres");
            return;
        }

        
        if (!Character.isLetter(c)) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar letras");
        }
    }//GEN-LAST:event_cajaMaternoAltasKeyTyped

    private void cajaCalleAltasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCalleAltasKeyTyped
        
        char c = evt.getKeyChar();

        
        if (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            return;
        }

        
        if (c == ' ') {
            return;
        }
        
        if (cajaCalleAltas.getText().length() >= 100) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar 100 caracteres");
            return;
        }

        
        if (!Character.isLetter(c)) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar letras");
        }
    }//GEN-LAST:event_cajaCalleAltasKeyTyped

    private void cajaNumAltasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaNumAltasKeyTyped
        
        char c = evt.getKeyChar();

        
        if (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            return;
        }

        
        if (cajaNumAltas.getText().length() >= 10) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar 10 numeros maximo");
            return;
        }

        
        if (!Character.isDigit(c)) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar números");
        }
    }//GEN-LAST:event_cajaNumAltasKeyTyped

    private void cajaColoniaAltasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaColoniaAltasKeyTyped
        char c = evt.getKeyChar();

        
        if (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            return;
        }

        
        if (c == ' ') {
            return;
        }
        
        if (cajaColoniaAltas.getText().length() >= 50) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar 50 caracteres");
            return;
        }

        
        if (!Character.isLetter(c)) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar letras");
        }
    }//GEN-LAST:event_cajaColoniaAltasKeyTyped

    private void cajaCodPostalAltasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCodPostalAltasKeyTyped
        char c = evt.getKeyChar();

        
        if (c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            return;
        }

        
        if (cajaCodPostalAltas.getText().length() >= 5) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar 5 numeros");
            return;
        }
        
        

        
        if (!Character.isDigit(c)) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo debes ingresar números");
        }
    }//GEN-LAST:event_cajaCodPostalAltasKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            JTable tablaDummy = new JTable();
            @Override
            public void run() {
                Dg_PacientesAltas dialog = new Dg_PacientesAltas(new javax.swing.JFrame(), true, tablaDummy);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPacAltas;
    private javax.swing.JButton btnRestablecerPacAltas;
    private javax.swing.JTextField cajaCalleAltas;
    private javax.swing.JTextField cajaCodPostalAltas;
    private javax.swing.JTextField cajaColoniaAltas;
    private javax.swing.JTextField cajaMaternoAltas;
    private javax.swing.JTextField cajaNombreAltas;
    private javax.swing.JTextField cajaNumAltas;
    private javax.swing.JTextField cajaPaternoAltas;
    private javax.swing.JTextField cajaSSNAltas;
    private javax.swing.JComboBox<String> cbSSNMedicoAltas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblNombreMedAltas;
    private javax.swing.JSpinner spEdadAltas;
    // End of variables declaration//GEN-END:variables
}
