/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Controlador.MedicoDAO;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author erick
 */

public class VentanaMedicos extends javax.swing.JPanel {

    /**
     * Creates new form PanelMedicos
     */
    
    MedicoDAO medicoDAO = MedicoDAO.getInstancia();
    public VentanaMedicos() {
        initComponents();
        
       
        
        
        medicoDAO.actualizarTabla(tablaRegMedicos);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAgregarMedicos = new javax.swing.JButton();
        btnEditarMedicos = new javax.swing.JButton();
        btnConsultarMedicos = new javax.swing.JButton();
        btnEliminarMedicos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegMedicos = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 244, 183));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\erick\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoFinal_FARMACIAS\\src\\main\\java\\img\\icons8-doctor-en-medicina-50.png")); // NOI18N
        jLabel1.setText("MEDICOS");

        btnAgregarMedicos.setBackground(new java.awt.Color(0, 153, 255));
        btnAgregarMedicos.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarMedicos.setIcon(new javax.swing.ImageIcon("C:\\Users\\erick\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoFinal_FARMACIAS\\src\\main\\java\\img\\icons8-agregar-archivo-50.png")); // NOI18N
        btnAgregarMedicos.setText("AGREGAR");
        btnAgregarMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMedicosActionPerformed(evt);
            }
        });

        btnEditarMedicos.setBackground(new java.awt.Color(0, 153, 255));
        btnEditarMedicos.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarMedicos.setIcon(new javax.swing.ImageIcon("C:\\Users\\erick\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoFinal_FARMACIAS\\src\\main\\java\\img\\icons8-crear-nuevo-50.png")); // NOI18N
        btnEditarMedicos.setText("MODIFICAR");
        btnEditarMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMedicosActionPerformed(evt);
            }
        });

        btnConsultarMedicos.setBackground(new java.awt.Color(0, 153, 255));
        btnConsultarMedicos.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultarMedicos.setIcon(new javax.swing.ImageIcon("C:\\Users\\erick\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoFinal_FARMACIAS\\src\\main\\java\\img\\icons8-aplicación-para-hacer-de-microsoft-50.png")); // NOI18N
        btnConsultarMedicos.setText("CONSULTAR");
        btnConsultarMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarMedicosActionPerformed(evt);
            }
        });

        btnEliminarMedicos.setBackground(new java.awt.Color(0, 153, 255));
        btnEliminarMedicos.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarMedicos.setIcon(new javax.swing.ImageIcon("C:\\Users\\erick\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoFinal_FARMACIAS\\src\\main\\java\\img\\icons8-basura-llena-50.png")); // NOI18N
        btnEliminarMedicos.setText("ELIMINAR");
        btnEliminarMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMedicosActionPerformed(evt);
            }
        });

        tablaRegMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "SSN", "NOMBRE", "APE_PATERNO", "APE_MATERNO", "ESPECIALIDAD", "AÑOS_EXPERIENCIA"
            }
        ));
        tablaRegMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaRegMedicosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablaRegMedicos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAgregarMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditarMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    javax.swing.JFrame parent = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

    
    
    private void btnAgregarMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMedicosActionPerformed
          JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
          Dg_MedicosAltas dialog = new Dg_MedicosAltas(parent, true, tablaRegMedicos); // modal
          dialog.setVisible(true);
          medicoDAO.actualizarTabla(tablaRegMedicos);
    }//GEN-LAST:event_btnAgregarMedicosActionPerformed

    private void btnEliminarMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMedicosActionPerformed
          JFrame parent2 = (JFrame) SwingUtilities.getWindowAncestor(this);
          Dg_MedicosBajas dialog = new Dg_MedicosBajas(parent2, true, tablaRegMedicos); // modal
          dialog.setVisible(true);
          medicoDAO.actualizarTabla(tablaRegMedicos);
    }//GEN-LAST:event_btnEliminarMedicosActionPerformed

    private void btnEditarMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMedicosActionPerformed
          JFrame parent3 = (JFrame) SwingUtilities.getWindowAncestor(this);
          Dg_MedicosCambios dialog = new Dg_MedicosCambios(parent3, true, tablaRegMedicos); // modal
          dialog.setVisible(true);
          medicoDAO.actualizarTabla(tablaRegMedicos);
    }//GEN-LAST:event_btnEditarMedicosActionPerformed

    private void btnConsultarMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarMedicosActionPerformed
          JFrame parent4 = (JFrame) SwingUtilities.getWindowAncestor(this);
          Dg_MedicosConsultas dialog = new Dg_MedicosConsultas(parent4, true, tablaRegMedicos); // modal
          dialog.setVisible(true);
          medicoDAO.actualizarTabla(tablaRegMedicos);
    }//GEN-LAST:event_btnConsultarMedicosActionPerformed

    private void tablaRegMedicosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRegMedicosMouseReleased
        String ssn = (String) tablaRegMedicos.getValueAt(tablaRegMedicos.getSelectedRow(), 0);
        //cajaSSN.setText(nc);
    }//GEN-LAST:event_tablaRegMedicosMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMedicos;
    private javax.swing.JButton btnConsultarMedicos;
    private javax.swing.JButton btnEditarMedicos;
    private javax.swing.JButton btnEliminarMedicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaRegMedicos;
    // End of variables declaration//GEN-END:variables
}
