/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Controlador.PacienteDAO;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author erick
 */
public class VentanaPacientes extends javax.swing.JPanel {

    /**
     * Creates new form VentanaPacientes
     */
    
    PacienteDAO pacienteDAO = PacienteDAO.getInstancia();
    public VentanaPacientes() {
        initComponents();
        
        pacienteDAO.actualizarTabla(tablaRegPacientes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAgregarPacientes = new javax.swing.JButton();
        btnEliminarPacientes = new javax.swing.JButton();
        btnEditarPacientes = new javax.swing.JButton();
        btnConsultarPacientes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegPacientes = new javax.swing.JTable();

        setBackground(new java.awt.Color(69, 104, 130));
        setPreferredSize(new java.awt.Dimension(695, 643));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PACIENTES");

        btnAgregarPacientes.setBackground(new java.awt.Color(102, 255, 51));
        btnAgregarPacientes.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarPacientes.setText("AGREGAR");
        btnAgregarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPacientesActionPerformed(evt);
            }
        });

        btnEliminarPacientes.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminarPacientes.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarPacientes.setText("ELIMINAR");
        btnEliminarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPacientesActionPerformed(evt);
            }
        });

        btnEditarPacientes.setBackground(new java.awt.Color(255, 153, 0));
        btnEditarPacientes.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarPacientes.setText("MODIFICAR");
        btnEditarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPacientesActionPerformed(evt);
            }
        });

        btnConsultarPacientes.setBackground(new java.awt.Color(0, 153, 255));
        btnConsultarPacientes.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultarPacientes.setText("CONSULTAR");
        btnConsultarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPacientesActionPerformed(evt);
            }
        });

        tablaRegPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SSN", "NOMBRE", "APE_PATERNO", "APE_MATERNO", "EDAD", "SSN_MEDICO_CABECERA", "CALLE", "NUMERO", "COLONIA", "CODIGO_POSTAL"
            }
        ));
        jScrollPane1.setViewportView(tablaRegPacientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnEditarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPacientesActionPerformed
        JFrame parent5 = (JFrame) SwingUtilities.getWindowAncestor(this);
        Dg_PacientesAltas dialog = new Dg_PacientesAltas(parent5, true, tablaRegPacientes);
        dialog.setVisible(true);
        pacienteDAO.actualizarTabla(tablaRegPacientes);
        
    }//GEN-LAST:event_btnAgregarPacientesActionPerformed

    private void btnEliminarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPacientesActionPerformed
        
        JFrame parent6 = (JFrame) SwingUtilities.getWindowAncestor(this);
        Dg_PacientesBajas dialog = new Dg_PacientesBajas(parent6, true, tablaRegPacientes);
        dialog.setVisible(true);
        pacienteDAO.actualizarTabla(tablaRegPacientes);
    }//GEN-LAST:event_btnEliminarPacientesActionPerformed

    private void btnEditarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPacientesActionPerformed
        
        JFrame parent7 = (JFrame) SwingUtilities.getWindowAncestor(this);
        Dg_PacientesCambios dialog = new Dg_PacientesCambios(parent7, true, tablaRegPacientes);
        dialog.setVisible(true);
        pacienteDAO.actualizarTabla(tablaRegPacientes);
    }//GEN-LAST:event_btnEditarPacientesActionPerformed

    private void btnConsultarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPacientesActionPerformed
        
        JFrame parent8 = (JFrame) SwingUtilities.getWindowAncestor(this);
        Dg_PacientesConsultas dialog = new Dg_PacientesConsultas(parent8, true, tablaRegPacientes);
        dialog.setVisible(true);
        pacienteDAO.actualizarTabla(tablaRegPacientes);
    }//GEN-LAST:event_btnConsultarPacientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPacientes;
    private javax.swing.JButton btnConsultarPacientes;
    private javax.swing.JButton btnEditarPacientes;
    private javax.swing.JButton btnEliminarPacientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaRegPacientes;
    // End of variables declaration//GEN-END:variables
}
